debian/tmp/scratchbox/tools/docs/logos usr/share/python-wifi
debian/tmp/scratchbox/tools/examples usr/share/doc/python-wifi
debian/tmp/scratchbox/tools/usr/lib
debian/tmp/scratchbox/tools/man usr/share
debian/tmp/scratchbox/tools/README usr/share/doc/python-wifi
debian/tmp/scratchbox/tools/docs/AUTHORS usr/share/doc/python-wifi
debian/tmp/scratchbox/tools/docs/BUGS usr/share/doc/python-wifi
debian/tmp/scratchbox/tools/docs/DEVEL.txt usr/share/doc/python-wifi
debian/tmp/scratchbox/tools/docs/feature_matrix_iwconfig.py.txt usr/share/doc/python-wifi
debian/tmp/scratchbox/tools/docs/feature_matrix_iwlist.py.txt usr/share/doc/python-wifi
debian/tmp/scratchbox/tools/docs/feature_matrix_wireless_extensions.txt usr/share/doc/python-wifi
debian/tmp/scratchbox/tools/docs/NEWS usr/share/doc/python-wifi
debian/tmp/scratchbox/tools/docs/ROADMAP usr/share/doc/python-wifi
debian/tmp/scratchbox/tools/docs/TODO usr/share/doc/python-wifi
